name: del remote ssh command
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: con-de.maitretech.com
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Change to the backend directory
            cd backend/volumes
            cat postgrest.conf
            config_file="postgrest.conf"
            # Original comma-separated string
            arr=$(grep -oP 'db-schemas\s*=\s*"\K[^"]+' "$config_file")

            # Value to filter out
            filter="wisdomschool"

            # Convert the string into an array
            IFS=',' read -ra arr_items <<< "$arr"

            # Filter the array
            result=""
            for item in "${arr_items[@]}"; do
                item=$(echo "$item" | xargs)
              if [[ "$item" != "$filter" ]]; then
                if [[ -n "$result" ]]; then
                  result+=", "
                fi
                result+="$item"
              fi
            done

            echo "$result"
            echo "db-schemas = \"$result\"" > "$config_file"
            cat postgrest.conf

            pwd
            psql --version
            # PGPASSWORD=your-super-secret-and-long-postgres-password psql -h con-de.maitretech.com -p 5433 -U postgres -d postgres -c "NOTIFY pgrst, 'reload config';"
            # PGPASSWORD=your-super-secret-and-long-postgres-password psql -h con-de.maitretech.com -p 5433 -U postgres -d postgres -c "NOTIFY pgrst, 'reload schema';"

