name: Backup Script for Medisparsh
on:
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: "30 10 * * *"
jobs:
  backup_schema_medisparsh:
    name: Backup Script for Medisparsh
    runs-on: ubuntu-latest

    steps:
      - name: Dump and upload schemas
        uses: appleboy/ssh-action@v1
        with:
          host: con-in.maitretech.com
          username: root
          key: ${{ secrets.SELF_HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "🚀 Starting schema exposure job..."
            ############################
            # Variables
            ############################
            DB_HOST="studio.maitretech.com"
            DB_NAME="medisparsh"
            DB_USER="postgres"
            DB_PORT="5432"


            DATE_TIME=$(date '+%Y-%m-%dT-%H:%M:%S')
            ONLY_DATE=$(date '+%Y-%m-%d')
            WORKDIR="$(pwd)"


            ############################
            # Fetch schemas list
            ############################
            echo "📥 Fetching schema list..."
            curl -s -X GET "https://abc.medisparsh.com/api/createOrg" \
            -H "Authorization: Bearer FaTvIeduiInc1nrBUILnlX1WpJUmkO6AG8NMp916s2B8Zv5eDymCaGX1Z94=" \
            | jq -r '.data[]?.slug // empty' > $(pwd)/project.txt


            ############################
            # Dump & upload dynamic schemas
            ############################
            while read -r schema; do
              schema=$(echo "$schema" | sed 's/\r//g')

              echo "🗄️ Dumping schema: ${schema}"
              # Check if schema exists
              exists=$(PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h studio.maitretech.com -p 5432 -U postgres -d medisparsh -tAc "SELECT 1 FROM information_schema.schemata WHERE schema_name='${schema}'")

              if [ "$exists" != "1" ]; then
                echo "Schema $schema does not exist. Skipping..."
                continue
              fi

              PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_dump -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" \
                --schema "${schema}" \
                -f "${schema}_${DATE_TIME}.sql"

              s3cmd put ${schema}_${DATE_TIME}.sql s3://medisparsh/medisparsh/${schema}/${ONLY_DATE}/

              echo "☁️ Uploaded schema: ${schema}"
            done < "${WORKDIR}/project.txt"

            ############################
            # Cleanup
            ############################
            rm -f project.txt *.sql

            echo "🧹 Cleanup completed"
            echo "🎉 All schema dumps and uploads completed successfully!"